---
title: "Test Adaptive Algorithms for Educational Games"
author: "George"
date: "7/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(liqueueR)
require(tidyverse)
```

## gloria's first try at priority queue update

```{r example-pq}
CHUNK_SIZE = 8
CHUNK_PRIORITY_INCREASE = .5
CORRECT_PRIORITY_INCREASE = 1
INCORRECT_PRIORITY_DECREASE = .5

# 70 trials per 5 mins, and exposure should be ~40 mins
NUM_TRIALS = 70 * 8 # realistic estimate of our intervention 

#q1 <- PriorityQueue$new() # for accessing data
#q2 <- PriorityQueue$new() # for accessing priority
literacy_stim = c(LETTERS, letters)
numeracy_stim = c(1:25, 0, 26:51)
# 0.5 for chance; 0.66 for 2U1D; 0.95 for solid learner
lit_prob_correct = rep(.5, length(literacy_stim)) # could model learning if we increase these
num_prob_correct = rep(.5, length(numeracy_stim)) 
# probs (say, if they get it correct + .1)

# R priority queue: >priority is higher priority (JS version < is higher)

# how many times each stim is selected
#literacy_stim_freq = rep(0, length(literacy_stim))
#numeracy_stim_freq = rep(0, length(numeracy_stim))
#names(literacy_stim_freq) = literacy_stim

#q <- PriorityQueue$new() # for accessing data

# construct priority queue 
build_priority_queue <- function(stim) {
  pr <- 0
  for (i in 1:length(stim)) {
    q$push(list(stimulus=stim[i], index=i, priority=pr), priority=pr)
    #q1$push(val, priority=pr)
    #q2$push(pr, priority=pr)
    if(i%%CHUNK_SIZE==0) pr = pr + CHUNK_PRIORITY_INCREASE
    pr <- pr - 0.01
  }
  return(q)
}

#lit_q <- build_priority_queue(literacy_stim)
#num_q <- build_priority_queue(numeracy_stim)



run_exp <- function(stimuli, prob_correct, num_trials = 100) {
  # consider adding NUM_FOILS that changes as we play--changes the probability of correct choice
  
  # track data we want to plot
  stim_dat <- tibble(stimulus = stimuli, 
                     prob_correct = prob_correct,
                             freq = 0, # how many times each stim occurs
                             correct = 0, # if we model learning, track this
                             start_priority = 0, 
                             cur_priority = 0)
  
  # initialize priorities
  pr = 0
  for(i in 1:nrow(stim_dat)) {
    if(i%%CHUNK_SIZE==0) pr = pr + CHUNK_PRIORITY_INCREASE
    pr <- pr - 0.01
    stim_dat[i,]$start_priority = pr
    stim_dat[i,]$cur_priority = pr
  }
  
# pop, simulate correct or not, push back
  for (t in seq(num_trials)) {
    curr_index = which(stim_dat$cur_priority==max(stim_dat$cur_priority)) #
    #curr_stim = stim_dat[curr_index,]
    
    stim_dat[curr_index,]$freq = stim_dat[curr_index,]$freq + 1
    
    #index = which(literacy_stim==curr_data$)
    #literacy_stim_freq[index] = literacy_stim_freq[index] + 1
    #literacy_stim_data[index,]$freq = literacy_stim_data[index,]$freq + 1
    
    randnum <- runif(1, min=0, max=1) # consider replacing with rbinom and using NFOILS to change probability of success
    if (randnum < stim_dat[curr_index,]$prob_correct) {
      stim_dat[curr_index,]$cur_priority = stim_dat[curr_index,]$cur_priority - 
        CORRECT_PRIORITY_INCREASE
      stim_dat[curr_index,]$correct = stim_dat[curr_index,]$correct + 1
      # update prob_correct? 
    } else {
      stim_dat[curr_index,]$cur_priority = stim_dat[curr_index,]$cur_priority - 
        INCORRECT_PRIORITY_DECREASE
    }
  }
  return(stim_dat)
}
# do couple types of simulation
# 1) baseline .5 random model, with no learning
lit_sim_pt5 = run_exp(literacy_stim, lit_prob_correct, num_trials = NUM_TRIALS)
num_sim_pt5 = run_exp(numeracy_stim, num_prob_correct, num_trials = NUM_TRIALS)

# 2) "realistic": better knowledge of easier stimuli
num_prob_correct = 1- seq(.01, 1, 1/length(numeracy_stim))

View(run_exp(numeracy_stim, num_prob_correct, num_trials = NUM_TRIALS))

# 3) some kind of learning... increase prob_correct as function of freq  (up to 1)


# plot freq, change in priority 
```
## Define the Stimuli and Difficulties

Our pilot will use upper- and lower-case letters, ordered by decreasing frequency (here ordered alphabetically for convenience).

```{r define-stimuli}

literacy_stim = c(LETTERS, letters)
numeracy_stim = c(1:25, 0, 26:51)


# priority queues (priority scale is arbitrary, but higher = easier)
litQ = data.frame(stim=literacy_stim, priority=seq(length(literacy_stim), 1))
numQ = data.frame(stim=numeracy_stim, priority=seq(length(numeracy_stim), 1))

```

## Define Adjustment Function



```{r pressure, echo=FALSE}


```


## Define Learners

Let's start with learners who have a fixed probability *r* of correctly responding to each stimulus.

